# dependencies needed for Binder
dependencies:
  - python=3.7
  - ipywidgets==7.5.1
  - jupyterlab==2.2.0
  - jupyterhub-singleuser==1.1.0
  - nbconvert==5.6.1
  - nbresuse==0.3.3
  - notebook==6.0.3
  - nteract_on_jupyter==2.1.3
  - sympy==1.7.1
  - matplotlib==3.3.3
  - numpy==1.19.0